<?php

/**
 * Implements hook_feeds_plugins().
 */
function feeds_comment_processor_feeds_plugins() {
  $path = drupal_get_path('module', 'feeds_comment_processor');

  $info = array();
  $info['FeedsCommentProcessor'] = array(
    'name' => 'Comment processor',
    'description' => 'Create and update comments.',
    'help' => 'Create and update comments from parsed content.',
    'handler' => array(
      'parent' => 'FeedsProcessor',
      'class' => 'FeedsCommentProcessor',
      'file' => 'FeedsCommentProcessor.inc',
      'path' => $path,
    ),
  );
  return $info;
}
