<?php

/**
 * @file
 * Update functions for feeds_comment_processor.module.
 */

/**
 * Implements hook_enable().
 */
function feeds_comment_processor_enable() {
  cache_clear_all('plugins:feeds:plugins', 'cache');
}

// TODO The old hook_update_N functions cannot be applied to Backdrop.
function feeds_comment_processor_update_7101(array &$sandbox) { }

// TODO The old hook_update_N functions cannot be applied to Backdrop.
function feeds_comment_processor_update_7102() { }

// TODO The old hook_update_N functions cannot be applied to Backdrop.
function feeds_comment_processor_update_7103() { }

// TODO The old hook_update_N functions cannot be applied to Backdrop.
function feeds_comment_processor_update_7104(array &$sandbox) { }
